id: P007053
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD152299
  title: སྒྲུང་རྒྱུད་དང་གླིང་སྒྲུང་རིག་པའི་རྣམ་བཤད།
  author: ''
  volumes:
    f975abc3ba234c93af293ec00274b957:
      image_group_id: I2PD20390
      title: ''
      volume_number: 1
      total_pages: 808
ebook_metadata:
  title: སྒྲུང་རྒྱུད་དང་གླིང་སྒྲུང་རིག་པའི་རྣམ་བཤད།
  author: ''
  sku: P007053
  cover: cover.jpg
  layers:
  - pagination
