id: P007053
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:38:40.381346
source_metadata:
  id: bdr:W1PD152299
  title: སྒྲུང་རྒྱུད་དང་གླིང་སྒྲུང་རིག་པའི་རྣམ་བཤད།
  author: ''
  volumes:
    60a114de8f574481872a8903dabbe4b6:
      image_group_id: I2PD20390
      title: Volume 1 of sgrung rgyud dang gling sgrung rig pa'i rnam bshad/
      volume_number: 1
      total_pages: 808
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
